=== jalyna/oakdex-pokedex/data/schemas/move.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "index_number": {
      "type": "integer"
    },
    "pp": {
      "type": "integer"
    },
    "max_pp": {
      "type": "integer"
    },
    "power": {
      "type": "integer"
    },
    "accuracy": {
      "type": "integer",
      "minimum": 0,
      "maximum": 100
    },
    "type": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "priority": {
      "type": "integer",
      "minimum": -7,
      "maximum": 7
    },
    "target": {
      "type": "string"
    },
    "critical_hit": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3
    },
    "makes_contact": {
      "type": "boolean"
    },
    "affected_by_protect": {
      "type": "boolean"
    },
    "affected_by_magic_coat": {
      "type": "boolean"
    },
    "affected_by_snatch": {
      "type": "boolean"
    },
    "affected_by_mirror_move": {
      "type": "boolean"
    },
    "affected_by_kings_rock": {
      "type": "boolean"
    },
    "names": {
      "type": "object",
      "properties": {
        "cz": {
          "type": "string"
        },
        "dk": {
          "type": "string"
        },
        "fr": {
          "type": "string"
        },
        "de": {
          "type": "string"
        },
        "gr": {
          "type": "string"
        },
        "it": {
          "type": "string"
        },
        "pl": {
          "type": "string"
        },
        "tr": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": [
        "en"
      ],
      "additionalProperties": false
    },
    "descriptions": {
      "type": "object",
      "properties": {
        "cz": {
          "type": "string"
        },
        "dk": {
          "type": "string"
        },
        "fr": {
          "type": "string"
        },
        "de": {
          "type": "string"
        },
        "gr": {
          "type": "string"
        },
        "it": {
          "type": "string"
        },
        "pl": {
          "type": "string"
        },
        "tr": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": [
        "en"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "index_number",
    "pp",
    "max_pp",
    "power",
    "accuracy",
    "type",
    "category",
    "priority",
    "target",
    "critical_hit",
    "makes_contact",
    "affected_by_protect",
    "affected_by_magic_coat",
    "affected_by_snatch",
    "affected_by_mirror_move",
    "affected_by_kings_rock",
    "names",
    "descriptions"
  ],
  "additionalProperties": false
}

=== jalyna/oakdex-pokedex/data/move/phantom_force.json
{
  "index_number": 566,
  "pp": 10,
  "max_pp": 16,
  "power": 90,
  "accuracy": 100,
  "category": "physical",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": true,
  "affected_by_protect": false,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": true,
  "names": {
    "fr": "Hantise",
    "de": "Phantomkraft",
    "it": "Spettrotuffo",
    "en": "Phantom Force"
  },
  "descriptions": {
    "en": "The user vanishes somewhere, then strikes the target on the next turn. This move hits even if the target protects itself."
  },
  "type": "Ghost"
}

=== jalyna/oakdex-pokedex/data/move/destiny_bond.json
{
  "index_number": 194,
  "pp": 5,
  "max_pp": 8,
  "power": 0,
  "accuracy": 0,
  "category": "status",
  "priority": 0,
  "target": "user",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": false,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "fr": "Prélèvem. Destin",
    "de": "Abgangsbund",
    "gr": "Κοινό Πεπρωμένο",
    "it": "Destinobbligato",
    "en": "Destiny Bond"
  },
  "descriptions": {
    "en": "A move that causes the opponent to faint if the user faints after using this move."
  },
  "type": "Ghost"
}

=== jalyna/oakdex-pokedex/data/move/rock_tomb.json
{
  "index_number": 317,
  "pp": 15,
  "max_pp": 24,
  "power": 60,
  "accuracy": 95,
  "category": "physical",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "fr": "Tomberoche",
    "de": "Felsgrab",
    "gr": "Ταφόπλακα",
    "it": "Rocciotomba",
    "pl": "Kamienny Grób",
    "en": "Rock Tomb"
  },
  "descriptions": {
    "en": "Stops the foe from moving with rocks and cuts Speed.*Stops the foe from moving with rocks. May lower Speed.*"
  },
  "type": "Rock"
}

=== jalyna/oakdex-pokedex/data/move/brine.json
{
  "index_number": 362,
  "pp": 10,
  "max_pp": 16,
  "power": 65,
  "accuracy": 100,
  "category": "special",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": true,
  "affected_by_kings_rock": true,
  "names": {
    "fr": "Saumure",
    "de": "Lake",
    "gr": "Άλμη",
    "it": "Acquadisale",
    "pl": "Bryza",
    "en": "Brine"
  },
  "descriptions": {
    "en": "If the foe’s HP is down to about half, this attack will hit with double the power.*If the foe’s HP is down to under half, this attack will hit with double the power.*"
  },
  "type": "Water"
}

=== jalyna/oakdex-pokedex/data/move/substitute.json
{
  "index_number": 164,
  "pp": 10,
  "max_pp": 16,
  "power": 0,
  "accuracy": 0,
  "category": "status",
  "priority": 0,
  "target": "user",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": false,
  "affected_by_magic_coat": false,
  "affected_by_snatch": true,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "dk": "Reserve",
    "fr": "Clonage",
    "de": "Delegator",
    "gr": "Υποκατάσταση",
    "it": "Sostituto",
    "pl": "Zastępca",
    "en": "Substitute"
  },
  "descriptions": {
    "en": "Uses 1/4 of the user's maximum HP to create a substitute that takes the opponent's attacks."
  },
  "type": "Normal"
}
