=== jalyna/oakdex-pokedex/data/schemas/move.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "index_number": {
      "type": "integer"
    },
    "pp": {
      "type": "integer"
    },
    "max_pp": {
      "type": "integer"
    },
    "power": {
      "type": "integer"
    },
    "accuracy": {
      "type": "integer",
      "minimum": 0,
      "maximum": 100
    },
    "type": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "priority": {
      "type": "integer",
      "minimum": -7,
      "maximum": 7
    },
    "target": {
      "type": "string"
    },
    "critical_hit": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3
    },
    "makes_contact": {
      "type": "boolean"
    },
    "affected_by_protect": {
      "type": "boolean"
    },
    "affected_by_magic_coat": {
      "type": "boolean"
    },
    "affected_by_snatch": {
      "type": "boolean"
    },
    "affected_by_mirror_move": {
      "type": "boolean"
    },
    "affected_by_kings_rock": {
      "type": "boolean"
    },
    "names": {
      "type": "object",
      "properties": {
        "cz": {
          "type": "string"
        },
        "dk": {
          "type": "string"
        },
        "fr": {
          "type": "string"
        },
        "de": {
          "type": "string"
        },
        "gr": {
          "type": "string"
        },
        "it": {
          "type": "string"
        },
        "pl": {
          "type": "string"
        },
        "tr": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": [
        "en"
      ],
      "additionalProperties": false
    },
    "descriptions": {
      "type": "object",
      "properties": {
        "cz": {
          "type": "string"
        },
        "dk": {
          "type": "string"
        },
        "fr": {
          "type": "string"
        },
        "de": {
          "type": "string"
        },
        "gr": {
          "type": "string"
        },
        "it": {
          "type": "string"
        },
        "pl": {
          "type": "string"
        },
        "tr": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": [
        "en"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "index_number",
    "pp",
    "max_pp",
    "power",
    "accuracy",
    "type",
    "category",
    "priority",
    "target",
    "critical_hit",
    "makes_contact",
    "affected_by_protect",
    "affected_by_magic_coat",
    "affected_by_snatch",
    "affected_by_mirror_move",
    "affected_by_kings_rock",
    "names",
    "descriptions"
  ],
  "additionalProperties": false
}

=== jalyna/oakdex-pokedex/data/move/pay_day.json
{
  "index_number": 6,
  "pp": 20,
  "max_pp": 32,
  "power": 40,
  "accuracy": 100,
  "category": "physical",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": true,
  "affected_by_kings_rock": true,
  "names": {
    "dk": "Kasse I",
    "fr": "Jackpot",
    "de": "Zahltag",
    "gr": "Φιλαργυρία",
    "it": "Giornopaga",
    "pl": "Dzień Zapłaty",
    "tr": "Ödeme Günü",
    "en": "Pay Day"
  },
  "descriptions": {
    "en": "A move that also nets money at the end of battle. How much depends on the attack frequency and level."
  },
  "type": "Normal"
}

=== jalyna/oakdex-pokedex/data/move/lock_on.json
{
  "index_number": 199,
  "pp": 5,
  "max_pp": 8,
  "power": 0,
  "accuracy": 0,
  "category": "status",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "fr": "Verrouillage",
    "de": "Zielschuss",
    "gr": "Κλείδωμα Στόχου",
    "it": "Localizza",
    "en": "Lock-On"
  },
  "descriptions": {
    "en": "An attack that locks on to the target to ensure that the next attack will hit without fail."
  },
  "type": "Normal"
}

=== jalyna/oakdex-pokedex/data/move/rain_dance.json
{
  "index_number": 240,
  "pp": 5,
  "max_pp": 8,
  "power": 0,
  "accuracy": 0,
  "category": "status",
  "priority": 0,
  "target": "everyone",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": false,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "dk": "Regndans",
    "fr": "Danse Pluie",
    "de": "Regentanz",
    "gr": "Χορός Βροχής",
    "it": "Pioggiadanza",
    "pl": "Taniec Deszczu",
    "en": "Rain Dance"
  },
  "descriptions": {
    "en": "Summons rain for five turns. While it is raining, the power of Water-type moves increases."
  },
  "type": "Water"
}

=== jalyna/oakdex-pokedex/data/move/spiky_shield.json
{
  "index_number": 596,
  "pp": 10,
  "max_pp": 16,
  "power": 0,
  "accuracy": 0,
  "category": "status",
  "priority": 4,
  "target": "user",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": false,
  "affected_by_magic_coat": false,
  "affected_by_snatch": true,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "fr": "Pico-DÃ©fense",
    "de": "Schutzstacheln",
    "it": "Agodifesa",
    "en": "Spiky Shield"
  },
  "descriptions": {
    "en": "In addition to protecting the user from attacks, this move also damages any attacker who makes direct contact."
  },
  "type": "Grass"
}

=== jalyna/oakdex-pokedex/data/move/arm_thrust.json
{
  "index_number": 292,
  "pp": 20,
  "max_pp": 32,
  "power": 15,
  "accuracy": 100,
  "category": "physical",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": true,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": true,
  "affected_by_kings_rock": true,
  "names": {
    "fr": "Cogne",
    "de": "Armstoß",
    "gr": "Ώθηση Χειρός",
    "it": "Sberletese",
    "pl": "Siła Ramion",
    "en": "Arm Thrust"
  },
  "descriptions": {
    "en": "Straight-arm punches that strike the foe 2 to 5 times."
  },
  "type": "Fighting"
}

=== jalyna/oakdex-pokedex/data/move/knock_off.json
{
  "index_number": 282,
  "pp": 25,
  "max_pp": 40,
  "power": 65,
  "accuracy": 100,
  "category": "physical",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": true,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "fr": "Sabotage",
    "de": "Abschlag",
    "gr": "Τράνταγμα",
    "it": "Privazione",
    "pl": "Nokaut",
    "en": "Knock Off"
  },
  "descriptions": {
    "en": "Knocks down the foe’s held item to prevent its use."
  },
  "type": "Dark"
}

=== jalyna/oakdex-pokedex/data/move/focus_punch.json
{
  "index_number": 264,
  "pp": 20,
  "max_pp": 32,
  "power": 150,
  "accuracy": 100,
  "category": "physical",
  "priority": -3,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": true,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "fr": "Mitra-Poing",
    "de": "Power-Punch",
    "gr": "Εστιασμένη Γροθιά",
    "it": "Centripugno",
    "pl": "Centrocios",
    "en": "Focus Punch"
  },
  "descriptions": {
    "en": "A powerful loyalty attack. The user flinches if hit.*Powerful, but makes the user flinch if hit by foe.*"
  },
  "type": "Fighting"
}

=== jalyna/oakdex-pokedex/data/move/spikes.json
{
  "index_number": 191,
  "pp": 20,
  "max_pp": 32,
  "power": 0,
  "accuracy": 0,
  "category": "status",
  "priority": 0,
  "target": "all_foes",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": false,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "fr": "Picots",
    "de": "Stachler",
    "gr": "Καρφιά",
    "it": "Punte",
    "pl": "Kolce",
    "en": "Spikes"
  },
  "descriptions": {
    "en": "An attack that scatters Spikes and injures opponent Pokémon when they switch."
  },
  "type": "Ground"
}
