=== jalyna/oakdex-pokedex/data/schemas/move.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "index_number": {
      "type": "integer"
    },
    "pp": {
      "type": "integer"
    },
    "max_pp": {
      "type": "integer"
    },
    "power": {
      "type": "integer"
    },
    "accuracy": {
      "type": "integer",
      "minimum": 0,
      "maximum": 100
    },
    "type": {
      "type": "string"
    },
    "category": {
      "type": "string"
    },
    "priority": {
      "type": "integer",
      "minimum": -7,
      "maximum": 7
    },
    "target": {
      "type": "string"
    },
    "critical_hit": {
      "type": "integer",
      "minimum": 0,
      "maximum": 3
    },
    "makes_contact": {
      "type": "boolean"
    },
    "affected_by_protect": {
      "type": "boolean"
    },
    "affected_by_magic_coat": {
      "type": "boolean"
    },
    "affected_by_snatch": {
      "type": "boolean"
    },
    "affected_by_mirror_move": {
      "type": "boolean"
    },
    "affected_by_kings_rock": {
      "type": "boolean"
    },
    "names": {
      "type": "object",
      "properties": {
        "cz": {
          "type": "string"
        },
        "dk": {
          "type": "string"
        },
        "fr": {
          "type": "string"
        },
        "de": {
          "type": "string"
        },
        "gr": {
          "type": "string"
        },
        "it": {
          "type": "string"
        },
        "pl": {
          "type": "string"
        },
        "tr": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": [
        "en"
      ],
      "additionalProperties": false
    },
    "descriptions": {
      "type": "object",
      "properties": {
        "cz": {
          "type": "string"
        },
        "dk": {
          "type": "string"
        },
        "fr": {
          "type": "string"
        },
        "de": {
          "type": "string"
        },
        "gr": {
          "type": "string"
        },
        "it": {
          "type": "string"
        },
        "pl": {
          "type": "string"
        },
        "tr": {
          "type": "string"
        },
        "en": {
          "type": "string"
        }
      },
      "required": [
        "en"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "index_number",
    "pp",
    "max_pp",
    "power",
    "accuracy",
    "type",
    "category",
    "priority",
    "target",
    "critical_hit",
    "makes_contact",
    "affected_by_protect",
    "affected_by_magic_coat",
    "affected_by_snatch",
    "affected_by_mirror_move",
    "affected_by_kings_rock",
    "names",
    "descriptions"
  ],
  "additionalProperties": false
}

=== jalyna/oakdex-pokedex/data/move/grudge.json
{
  "index_number": 288,
  "pp": 5,
  "max_pp": 8,
  "power": 0,
  "accuracy": 0,
  "category": "status",
  "priority": 0,
  "target": "user",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": false,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "fr": "Rancune",
    "de": "Nachspiel",
    "gr": "Κατάρα",
    "it": "Rancore",
    "en": "Grudge"
  },
  "descriptions": {
    "en": "If the user faints, deletes the PP of the final move."
  },
  "type": "Ghost"
}

=== jalyna/oakdex-pokedex/data/move/echoed_voice.json
{
  "index_number": 497,
  "pp": 15,
  "max_pp": 24,
  "power": 40,
  "accuracy": 100,
  "category": "special",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": true,
  "names": {
    "fr": "Ã‰cho",
    "de": "Widerhall",
    "it": "Echeggiavoce",
    "en": "Echoed Voice"
  },
  "descriptions": {
    "en": "The user attacks the target with an echoing voice. If this move is used every turn, it does greater damage."
  },
  "type": "Normal"
}

=== jalyna/oakdex-pokedex/data/move/thunder_wave.json
{
  "index_number": 86,
  "pp": 20,
  "max_pp": 32,
  "power": 0,
  "accuracy": 100,
  "category": "status",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "dk": "Tordenbølge",
    "fr": "Cage-Éclair",
    "de": "Donnerwelle",
    "gr": "Κύμα Ηλεκτρομαγνητισμού",
    "it": "Tuononda",
    "pl": "Fala Grzmotu",
    "tr": "Yıldırım Dalgası",
    "en": "Thunder Wave"
  },
  "descriptions": {
    "en": "A special move that causes paralysis. When paralyzed, the victim has a one-in-four chance of immobility."
  },
  "type": "Electric"
}

=== jalyna/oakdex-pokedex/data/move/whirlpool.json
{
  "index_number": 250,
  "pp": 15,
  "max_pp": 24,
  "power": 35,
  "accuracy": 85,
  "category": "special",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": true,
  "names": {
    "fr": "Siphon",
    "de": "Whirlpool",
    "gr": "Δίνη",
    "it": "Mulinello",
    "pl": "Wir Wodny",
    "en": "Whirlpool"
  },
  "descriptions": {
    "en": "Lasts two to five turns. Foe becomes trapped in a vortex, making it impossible to switch."
  },
  "type": "Water"
}

=== jalyna/oakdex-pokedex/data/move/wild_charge.json
{
  "index_number": 528,
  "pp": 15,
  "max_pp": 24,
  "power": 90,
  "accuracy": 100,
  "category": "physical",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": true,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": true,
  "names": {
    "fr": "Éclair Fou",
    "de": "Stromstoß",
    "it": "Sprizzalampo",
    "pl": "Dzika Energia",
    "en": "Wild Charge"
  },
  "descriptions": {
    "en": "The user shrouds itself in electricity and smashes into its target. It also damages the user a little."
  },
  "type": "Electric"
}

=== jalyna/oakdex-pokedex/data/move/forest_s_curse.json
{
  "index_number": 571,
  "pp": 20,
  "max_pp": 32,
  "power": 0,
  "accuracy": 100,
  "category": "status",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "fr": "Mal√©fice Sylvain",
    "de": "Waldesfluch",
    "it": "Boscomalocchio",
    "en": "Forest's Curse"
  },
  "descriptions": {
    "en": "The user puts a forest curse on the target. Afflicted targets are now Grass type as well."
  },
  "type": "Grass"
}

=== jalyna/oakdex-pokedex/data/move/autotomize.json
{
  "index_number": 475,
  "pp": 15,
  "max_pp": 24,
  "power": 0,
  "accuracy": 0,
  "category": "status",
  "priority": 0,
  "target": "user",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": false,
  "affected_by_magic_coat": false,
  "affected_by_snatch": true,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": false,
  "names": {
    "fr": "All√®gement",
    "de": "Autotomie",
    "it": "Sganciapesi",
    "en": "Autotomize"
  },
  "descriptions": {
    "en": "The user sheds part of its body to make itself lighter and sharply raise its Speed stat."
  },
  "type": "Steel"
}

=== jalyna/oakdex-pokedex/data/move/hydro_cannon.json
{
  "index_number": 308,
  "pp": 5,
  "max_pp": 8,
  "power": 150,
  "accuracy": 90,
  "category": "special",
  "priority": 0,
  "target": "target",
  "critical_hit": 0,
  "makes_contact": false,
  "affected_by_protect": true,
  "affected_by_magic_coat": false,
  "affected_by_snatch": false,
  "affected_by_mirror_move": false,
  "affected_by_kings_rock": true,
  "names": {
    "fr": "Hydroblast",
    "de": "Aquahaubitze",
    "gr": "Υδραυλικό Ολμοβόλο",
    "it": "Idrocannone",
    "pl": "Hydrodziało",
    "en": "Hydro Cannon"
  },
  "descriptions": {
    "en": "Powerful, but leaves the user immobile the next turn."
  },
  "type": "Water"
}
